from __future__ import annotations

from typing import Any

BREWMASTER_MODULES: list[dict[str, Any]] = [
    {
        "id": "REQ-AUTH",
        "name": "Usuarios y auth",
        "use_cases": ["UC-ALT-03"],
        "screens": ["P-01", "P-02", "P-30"],
        "entities": ["users", "roles", "permissions", "role_permissions", "audit_logs", "password_reset_tokens"],
        "acceptance": "login, JWT, roles, CRUD usuarios y auditoria de accesos",
    },
    {
        "id": "REQ-INS",
        "name": "Insumos",
        "use_cases": ["UC-INS-01", "UC-INS-02", "UC-INS-03", "UC-INS-04", "UC-INS-05", "UC-INS-06"],
        "screens": ["P-04", "P-05", "P-06", "P-07", "P-08", "P-09", "P-12"],
        "entities": ["suppliers", "warehouses", "supply_categories", "supplies", "supply_movements", "supply_entries", "notification_queue"],
        "acceptance": "CRUD, Kardex trazable, alertas de stock bajo con correo e intervalo respetado",
    },
    {
        "id": "REQ-REC",
        "name": "Recetas",
        "use_cases": ["UC-REC-01", "UC-REC-02"],
        "screens": ["P-10", "P-11", "P-13"],
        "entities": ["beer_styles", "presentation_types", "recipes", "recipe_ingredients"],
        "acceptance": "CRUD, calculo de costo, clonado y bloqueo si tiene lotes activos",
    },
    {
        "id": "REQ-PROD",
        "name": "Produccion",
        "use_cases": ["UC-PROD-01", "UC-PROD-02", "UC-PROD-03", "UC-PROD-04"],
        "screens": ["P-14", "P-15", "P-16", "P-17", "P-19"],
        "entities": ["production_batches", "batch_quality_checks", "waste_records", "batch_supply_snapshots"],
        "acceptance": "crear lote, completar con descuento de insumos, calidad, merma y costo calculado",
    },
    {
        "id": "REQ-PRO",
        "name": "Inventario productos",
        "use_cases": ["UC-PRO-01", "UC-PRO-02"],
        "screens": ["P-18"],
        "entities": ["finished_products", "product_movements"],
        "acceptance": "stock actualizado al completar lote, precio editable, Kardex trazable",
    },
    {
        "id": "REQ-VTA",
        "name": "Ventas",
        "use_cases": ["UC-VTA-01", "UC-VTA-02", "UC-VTA-03", "UC-VTA-04", "UC-VTA-05"],
        "screens": ["P-20", "P-21", "P-22", "P-23"],
        "entities": ["customer_types", "customers", "product_prices", "sales", "sale_items", "stock_reservations"],
        "acceptance": "venta con stock validado, ganancia calculada, Kardex y reservas",
    },
    {
        "id": "REQ-COM",
        "name": "Compras",
        "use_cases": ["UC-COM-01", "UC-COM-02"],
        "screens": ["P-24", "P-25"],
        "entities": ["purchase_orders", "purchase_order_items"],
        "acceptance": "orden, recepcion parcial/total y entrada de inventario automatica",
    },
    {
        "id": "REQ-EQU",
        "name": "Equipos",
        "use_cases": ["UC-EQU-01", "UC-EQU-02"],
        "screens": ["P-26", "P-27"],
        "entities": ["equipment_types", "equipment", "equipment_movements"],
        "acceptance": "CRUD, historial de mantenimientos y alerta de revision vencida",
    },
    {
        "id": "REQ-FIN",
        "name": "Finanzas",
        "use_cases": ["UC-FIN-01", "UC-FIN-02", "UC-FIN-03"],
        "screens": ["P-28", "P-29"],
        "entities": ["expense_categories", "operational_expenses", "monthly_goals"],
        "acceptance": "gastos operativos, reportes financieros basicos y metas mensuales",
    },
    {
        "id": "REQ-REP",
        "name": "Dashboard y reportes",
        "use_cases": ["UC-REP-01", "UC-REP-02"],
        "screens": ["P-03", "P-29"],
        "entities": ["export_jobs"],
        "acceptance": "KPIs reales, graficos, alertas operacionales y reportes exportables",
    },
    {
        "id": "REQ-ALT",
        "name": "Configuracion y alertas",
        "use_cases": ["UC-ALT-01", "UC-ALT-02", "UC-ALT-03"],
        "screens": ["P-30"],
        "entities": ["settings", "smtp_config", "notification_queue", "monthly_goals"],
        "acceptance": "SMTP cifrado, cola, reintentos, metas, usuarios y roles",
    },
]


BREWMASTER_SCREENS: list[dict[str, Any]] = [
    {"id": "P-01", "name": "Login", "module": "Auth", "route": "/login"},
    {"id": "P-02", "name": "Recuperar contrasena", "module": "Auth", "route": "/password/recover"},
    {"id": "P-03", "name": "Dashboard general", "module": "Dashboard", "route": "/"},
    {"id": "P-04", "name": "Listado de insumos", "module": "Insumos", "route": "/supplies"},
    {"id": "P-05", "name": "Formulario de insumo", "module": "Insumos", "route": "/supplies/:id"},
    {"id": "P-06", "name": "Kardex de insumo", "module": "Insumos", "route": "/supplies/:id/kardex"},
    {"id": "P-07", "name": "Entrada de insumos", "module": "Insumos", "route": "/supply-entries/new"},
    {"id": "P-08", "name": "Listado de proveedores", "module": "Proveedores", "route": "/suppliers"},
    {"id": "P-09", "name": "Formulario de proveedor", "module": "Proveedores", "route": "/suppliers/:id"},
    {"id": "P-10", "name": "Listado de recetas", "module": "Recetas", "route": "/recipes"},
    {"id": "P-11", "name": "Formulario de receta", "module": "Recetas", "route": "/recipes/:id"},
    {"id": "P-12", "name": "Listado de bodegas", "module": "Maestros", "route": "/warehouses"},
    {"id": "P-13", "name": "Tipos de presentacion", "module": "Maestros", "route": "/presentation-types"},
    {"id": "P-14", "name": "Listado de lotes de produccion", "module": "Produccion", "route": "/batches"},
    {"id": "P-15", "name": "Formulario de lote de produccion", "module": "Produccion", "route": "/batches/:id"},
    {"id": "P-16", "name": "Detalle de lote", "module": "Produccion", "route": "/batches/:id/detail"},
    {"id": "P-17", "name": "Control de calidad de lote", "module": "Produccion", "route": "/batches/:id/quality"},
    {"id": "P-18", "name": "Inventario de productos terminados", "module": "Inventario productos", "route": "/finished-products"},
    {"id": "P-19", "name": "Registro de mermas", "module": "Mermas", "route": "/waste-records/new"},
    {"id": "P-20", "name": "Listado de clientes", "module": "Ventas", "route": "/customers"},
    {"id": "P-21", "name": "Formulario de cliente", "module": "Ventas", "route": "/customers/:id"},
    {"id": "P-22", "name": "Formulario de venta", "module": "Ventas", "route": "/sales/new"},
    {"id": "P-23", "name": "Reservas de stock", "module": "Ventas", "route": "/reservations"},
    {"id": "P-24", "name": "Ordenes de compra", "module": "Compras", "route": "/purchase-orders"},
    {"id": "P-25", "name": "Recepcion de compra", "module": "Compras", "route": "/purchase-orders/:id/receive"},
    {"id": "P-26", "name": "Listado de equipos", "module": "Equipos", "route": "/equipment"},
    {"id": "P-27", "name": "Historial de mantenimiento", "module": "Equipos", "route": "/equipment/:id/history"},
    {"id": "P-28", "name": "Gastos operativos", "module": "Finanzas", "route": "/expenses"},
    {"id": "P-29", "name": "Reportes financieros y operacionales", "module": "Reportes", "route": "/reports"},
    {"id": "P-30", "name": "Configuracion SMTP, usuarios y roles", "module": "Configuracion", "route": "/settings"},
]


CRUD_RESOURCES = [
    "users",
    "roles",
    "suppliers",
    "warehouses",
    "supplies",
    "supply-entries",
    "recipes",
    "presentation-types",
    "batches",
    "finished-products",
    "waste-records",
    "customers",
    "sales",
    "reservations",
    "purchase-orders",
    "equipment",
    "equipment-movements",
    "operational-expenses",
    "monthly-goals",
    "reports",
    "settings",
]


ACTION_ENDPOINTS = [
    ("POST", "/api/v1/auth/login", "auth.login"),
    ("POST", "/api/v1/auth/refresh", "auth.refresh"),
    ("POST", "/api/v1/auth/password-reset/request", "auth.password_reset_request"),
    ("POST", "/api/v1/auth/password-reset/confirm", "auth.password_reset_confirm"),
    ("PATCH", "/api/v1/supplies/{id}/toggle-status", "supplies.toggle_status"),
    ("GET", "/api/v1/supplies/{id}/kardex", "supplies.kardex"),
    ("POST", "/api/v1/recipes/{id}/clone", "recipes.clone"),
    ("POST", "/api/v1/batches/{id}/complete", "batches.complete"),
    ("POST", "/api/v1/batches/{id}/cancel", "batches.cancel"),
    ("POST", "/api/v1/batches/{id}/quality-check", "batches.quality_check"),
    ("PATCH", "/api/v1/finished-products/{id}/price", "finished_products.price"),
    ("POST", "/api/v1/sales/{id}/void", "sales.void"),
    ("POST", "/api/v1/reservations/{id}/consume", "reservations.consume"),
    ("POST", "/api/v1/reservations/{id}/release", "reservations.release"),
    ("POST", "/api/v1/purchase-orders/{id}/send", "purchase_orders.send"),
    ("POST", "/api/v1/purchase-orders/{id}/receive", "purchase_orders.receive"),
    ("POST", "/api/v1/reports/export", "reports.export"),
    ("POST", "/api/v1/settings/smtp/test", "settings.smtp_test"),
]


TRANSACTIONAL_RESOURCES = {
    "supply-entries",
    "batches",
    "waste-records",
    "sales",
    "reservations",
    "purchase-orders",
}
