from __future__ import annotations

from .harness import AgentSpec

WORKFLOW_VERSION = "wf.webforge.sdd.v1"
WORKFLOW_PHASES = [
    "intake",
    "constitution",
    "specify",
    "clarify",
    "checklist",
    "context",
    "plan",
    "tasks",
    "analyze",
    "implement",
    "validate",
    "security",
    "pr_handoff",
    "deploy_checkpoint",
    "observe",
    "close",
]


PHASE_AGENTS: dict[str, AgentSpec] = {
    "intake": AgentSpec("agent.intake", "intake", "WorkOrder"),
    "constitution": AgentSpec("agent.constitution", "constitution", "Constitution"),
    "specify": AgentSpec("agent.spec_parser", "specify", "Spec"),
    "clarify": AgentSpec("agent.clarifier", "clarify", "Clarifications"),
    "checklist": AgentSpec("agent.requirements_qa", "checklist", "Checklist"),
    "context": AgentSpec("agent.context_rag", "context", "ContextPack"),
    "plan": AgentSpec("agent.architect_planner", "plan", "Plan"),
    "tasks": AgentSpec("agent.task_planner", "tasks", "Tasks"),
    "analyze": AgentSpec("agent.consistency_reviewer", "analyze", "AnalyzeReport"),
    "implement": AgentSpec(
        "agent.implementer",
        "implement",
        "ImplementationReport",
        allowed_tools=("tool.sandbox.dev_materialize",),
    ),
    "validate": AgentSpec(
        "agent.qa",
        "validate",
        "ValidationReport",
        allowed_tools=("tool.policy.static", "tool.validation.artifacts"),
    ),
    "security": AgentSpec(
        "agent.security",
        "security",
        "SecurityReview",
        allowed_tools=("tool.security.secrets", "tool.security.deps", "tool.sbom.generate"),
    ),
    "pr_handoff": AgentSpec("agent.integrator_pr", "pr_handoff", "PRBundle"),
    "deploy_checkpoint": AgentSpec("agent.release_sre", "deploy_checkpoint", "DeployCheckpoint"),
    "observe": AgentSpec("agent.observability_cost", "observe", "ObservabilityReport"),
    "close": AgentSpec("agent.close", "close", "FinalReport"),
}


REQUIRED_FINAL_ARTIFACTS = [
    "state.json",
    "log.jsonl",
    "evidence-register.md",
    "context-pack.json",
    "validation-report.json",
    "security-review.md",
    "traceability-matrix.md",
    "billing-ledger.json",
    "factory-skill-manifest.json",
    "factory-tool-manifest.json",
    "roadmap.md",
    "roadmap.json",
    "milestone-plan.json",
    "milestone-state.json",
    "milestone-validation-report.json",
    "milestone-gate-report.json",
    "milestone-evidence.md",
    "regression-report.json",
    "incremental-traceability.md",
    "qa-promotion-report.json",
    "frontend-template-manifest.json",
    "frontend-template-policy.md",
    "project-isolation-policy.md",
    "project-manifest.json",
    "project-memory-policy.json",
    "project-sandboxes.json",
    "dev-materialization-manifest.json",
    "final-report.json",
]

KNOWN_OUTPUT_ARTIFACTS = {
    "Aprendizaje.md",
    "ERRORS.md",
    "PRBundle.md",
    "agent-manifest.json",
    "analyze-report.md",
    "approval-matrix.md",
    "billing-ledger.json",
    "billing-policy.yaml",
    "checklist.md",
    "claim-map.md",
    "clarifications.md",
    "constitution.md",
    "context-pack.json",
    "dependency-report.json",
    "deploy-plan.md",
    "dev-materialization-manifest.json",
    "diff-report.json",
    "evidence-register.md",
    "factory-skill-manifest.json",
    "factory-tool-manifest.json",
    "final-report.json",
    "frontend-template-manifest.json",
    "frontend-template-policy.md",
    "implementation-report.md",
    "log-completeness-report.json",
    "log.jsonl",
    "mcp-invocations.jsonl",
    "mcp-policy.json",
    "mcp-policy.yaml",
    "memory-report.json",
    "milestone-evidence.md",
    "milestone-gate-report.json",
    "milestone-plan.json",
    "milestone-state.json",
    "milestone-validation-report.json",
    "metrics.json",
    "phase-ledger.json",
    "plan.md",
    "principle-ledger.json",
    "project-isolation-policy.md",
    "project-manifest.json",
    "project-memory-policy.json",
    "project-sandboxes.json",
    "qa-promotion-report.json",
    "rag-index-manifest.json",
    "regression-report.json",
    "rollback-plan.md",
    "roadmap.json",
    "roadmap.md",
    "sbom.json",
    "secrets-report.json",
    "security-review.md",
    "sandbox-policy.md",
    "slo-policy.md",
    "spec.md",
    "state.json",
    "tasks.md",
    "tool-logs.jsonl",
    "tool-registry.json",
    "traceability-matrix.md",
    "validation-report.json",
    "work_order.json",
    "workflow.yaml",
}
